### ISSUE TITLE
Breaking changes in google sign in plugin

### ISSUE THREAD

**Issue by jasonlaw** [AndriousSolutions/auth#12]
Hi Greg,

Thanks for another great package from you.
I have just tried the Auth package but encountered the following error.

![image](https://user-images.githubusercontent.com/107820/69603002-43dbd880-1054-11ea-9d2d-e91b3f78ac41.png)

It looks like there is some braking changes in google sign in plug in.

Could you please take a look?

Thanks again.

**Comment by Andrious** [comment]
Version 4.0.1 is now available with the **breaking change** now fixed.

**Comment by jasonlaw** [comment]
Hi Greg,

Thanks for the quick fixed, I see the error is gone now.
Btw, I have one question, suppose my app only want to support for Google and Facebook login, do I still need the firebase configuration? If possible I would prefer to minimize the dependency.

Thanks again!

**Comment by Andrious** [comment]
As it stands, this library works intimately with Firebase and merely uses Google and Facebook to 'sign into' Firebase authentication.
