### ISSUE TITLE
Can I Contribute logo for "Auth" ?

### ISSUE THREAD

**Issue by iqbalhood** [AndriousSolutions/auth#16]
Hello @Andrious , Can I Contribute to make Logo For This Project ?

**Comment by Andrious** [comment]
A Logo?  An interesting request.  

I will ask you to offer your sample or samples and I will decide it be accepted or not.

How about that?

**Comment by iqbalhood** [comment]
Okay sir, you can see a number of logo portfolios that I made in several open source projects on my instagram.
https://www.instagram.com/iqbalhood/

Please let me know if you are interested. (this is a free contribution)

**Comment by Andrious** [comment]
Thanks. Another time my friend.
