### ISSUE TITLE
Error: Type 'Auth' not found.

### ISSUE THREAD

**Issue by mark-zs** [AndriousSolutions/auth#17]
Hi can't get this working.  Compiling my flutter always gives
'Error: Type 'Auth' not found.'
Even though I included the dependency auth:
Thanks!

**Comment by Andrious** [comment]
Hi there, zvischreiber. 

Without looking at the code, I have only the error message and what you described. You may have included the dependency, but don't forget to then import it in the .dart file where you're using  Auth:

import 'package:auth/auth.dart';

The message, 'Error: Type 'Auth' not found.', suggests you haven't imported the file properly or at all.
In Flutter, you always have to import in the .dart file you're working with, zvischreiber.

**Comment by mark-zs** [comment]
Thanks for your response!  I am using the example project from your github
project.  The only change is that I have

dependencies:
  auth:

(without the local path that you have)

There are no problems in Dart Analysis and IntelliJ is happy with the
files.  But when I do "flutter build web" I get

Error: Type 'Auth' not found.
  Auth auth;
  ^^^^
lib/main.dart:30:3:

**Comment by Andrious** [comment]
Oh I see. 
Let's try a couple of things. 
First, let's explicitly specify the 'major version number' for the library package.
It's currently up to 5.

```
  auth: ^5.0.0
```

In the file, lib/main.dart:11:3:, if the import statement is currently with the 'if' statement:
```
import 'package:auth/auth.dart'
    if (dart.library.html) 'package:auth/auth_web.dart';
```
I would suggest changing the import statement to the following:
```
import 'package:auth/auth.dart';
```

**Comment by mark-zs** [comment]
Thanks for your kind help.

It worked to some extent!  It compiles now and one time I was able to open
it in debug mode.   (Just I need a client_id which I have to do)

But the second time (without changing anything at all!) I got

The following JSNoSuchMethodError was thrown building Builder:
TypeError: Cannot read property 'app' of undefined

The relevant error-causing widget was:
  MaterialApp file:///C:/Users/Zvi/IdeaProjects/example/lib/main.dart:15:5

**Comment by mark-zs** [comment]
Hmm now I'm getting
  Cannot read property 'app' of undefined

Again this is with your standard example (with just the change to the
import that you suggested).  I have a feeling maybe I need to configure
something for my Firebase instance but didn't see any instructions or TODOs
in the example code.

Any help would be appreciated!

Thanks

Zvi

**Comment by Andrious** [comment]
Let's see if I can help you in the right direction.

What IDE are you using? Android Studio?

Would you attach a screenshot of the error message you received?

**Comment by mark-zs** [comment]
It's working now thanks
