### ISSUE TITLE
Flutter facebook login uses deprecated Api

### ISSUE THREAD

**Issue by sallypeters** [AndriousSolutions/auth#18]
Hi - the plugin that you use for Facebook login uses a deprecated API - UIWebView. This has been deprecated since April 2020, meaning any NEW apps submitted after this date will be rejected. It will be great if we have a choice to use a native facebook solution or your old web flow approach.

**Comment by Andrious** [comment]
Thanks, Sally, I'll look into it. Of course, I would like to use an updated native facebook solution.

**Comment by Andrious** [comment]
Ok. The plugin originally used appears to be no longer supported. I've turned to another author who just released their own Facebook plugin. 

There's a new Auth library package now available. Version 6.0.0. Note, its permissions are not a List of Strings like the original plugin but a list of predefined values: 
[facebook_permission.dart](https://github.com/Innim/flutter_login_facebook/blob/c3645a398a65884654a7720561edf47e3c7a81f7/lib/src/models/facebook_permission.dart#L6) 

Cheers

**Comment by sallypeters** [comment]
Hi - thank you. I have used DIRECTLY the new native facebook plugin that you are now using in your plugin and it works well , plus does not use any deprecated API.  

Furthermore, just so you know - the Twitter plugin that you are using ALSO has the same deprecated UIWebView.

**Comment by Andrious** [comment]
Excellent. Wonderful to hear.  Indeed, the Twitter plugin is the next concern. 
Good luck in your endeavours.
