### ISSUE TITLE
firebase_auth ^0.18.0+1

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/auth#22]
Could you please upgrade firebase_auth dependency? Thank you.

**Comment by Andrious** [comment]
Yes, I will.

**Comment by Andrious** [comment]
The upgrade will be completed shortly. Note, their latest upgrade to firebase_auth 0.18.0+1 has been extensive and, in fact, involves a number of **BREAKS** in the codebase. Auth's version number will reflect these 'major' changes with 7.0.0.

Admittedly, I have performed only preliminary tests. 
Therefore, please notify me promptly if there are any issues.

## 7.0.0
 September 02, 2020
- Upgrade to firebase_auth 0.18.0+1
- **BREAKING:** The FirebaseUser class has been renamed to User.
- currentUser() to getter currentUser.
- **DEPRECATED:** updatePhoneNumberCredential(); to updatePhoneNumber();
- **BREAKING:** Accessing the current user via currentUser() is now synchronous via the currentUser getter.
- **BREAKING:** isSignInWithEmailLink() is now synchronous.
- **BREAKING:** unlinkFromProvider() no longer functional.
- **DEPRECATED:** FirebaseAuth.fromApp() is now deprecated in favor of FirebaseAuth.instanceFor().
- **DEPRECATED:** onAuthStateChanged has been deprecated in favor of authStateChanges().
