### ISSUE TITLE
Support firebase_auth ^0.20.0

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/auth#24]
```
Because auth 7.3.1 depends on firebase_auth ^0.18.0 and no versions of auth match >7.3.1 <8.0.0, auth ^7.3.1 requires firebase_auth ^0.18.0.
```

**Comment by Andrious** [comment]
Yes, I will release an update immediately.

**Comment by Andrious** [comment]
I've improved the package dependency so we don't have this problem in the future.
The syntax below now allows for the given version or greater when updates come available and not be out of reach.
firebase_core: '>=0.7.0'
firebase_auth: '>=0.20.0'

**Comment by Andrious** [comment]
version 7.3.2 is now available.
