### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/auth#26]
```
Because auth >=7.3.2 depends on firebase_core >=0.7.0 <1.0.0 and auth >=7.0.0 <7.3.2 depends on firebase_auth ^0.18.0, auth >=7.0.0 requires firebase_core >=0.7.0 <1.0.0 or firebase_auth ^0.18.0.
And because ... depends on auth ^7.0.0, either firebase_core >=0.7.0 <1.0.0 or firebase_auth ^0.18.0.
So, because ... depends on both firebase_auth ^1.0.0 and firebase_core ^1.0.0, version solving failed.
pub finished with exit code 1
```

**Comment by Andrious** [comment]
What depends on firebase_auth ^1.0.0 and firebase_core ^1.0.0?
`So, because ... depends on both firebase_auth ^1.0.0 and firebase_core ^1.0.0, version solving failed.`

 Just as a test, let's return to an older version of auth and see if that helps
```
dependencies:
  auth: ^7.3.1
```

**Comment by deadsoul44** [comment]
My app depends on those packages. I just removed the name of my app. 

```
  # https://pub.dev/packages/firebase_core
  firebase_core: '>=0.7.0 <1.0.0'

  # https://pub.dartlang.org/packages/firebase_auth
  firebase_auth: '>=0.20.0 <1.0.0'
```

`Auth` is incompatible with `firebase_auth ^1.0.0 and firebase_core ^1.0.0`?

**Comment by Andrious** [comment]
I see.  No worries. One moment.

**Comment by Andrious** [comment]
The latest Auth package has been now been published.
Auth 7.4.0  has its dependencies now up-to-date.
Please, confirm its success and then close this issue.

Greg

**Comment by deadsoul44** [comment]
It is solved. Thank you very much.
