### ISSUE TITLE
Use twitter_login instead of flutter_twitter

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/auth#27]
Use `twitter_login` which supports null-safety instead of `flutter_twitter` which was updated more than 2 years ago.

https://pub.dev/packages/twitter_login

**Comment by Andrious** [comment]
I will look into this Friday.

**Comment by Andrious** [comment]
Version 8.0.0-pre is a 'testing' release.  Please, confirm that this is working for you before I then supply a formal version release.

**Comment by deadsoul44** [comment]
Actually I dont use twitter login in my app. Just wanted this due to null safety.

**Comment by Andrious** [comment]
Fair enough.  Please, use it as you would.  If anything, just to make sure this 'null safety' version works for you.

Further testing is required before it's ready for a full release.

Greg.
