### ISSUE TITLE
upgrade to firebase_auth 2.0.0

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/auth#29]
firebase_auth 2.0.0 is released. It could be great to upgrade the dependency. Thank you.

**Comment by Andrious** [comment]
Yes, I'll set up a community repo one day in the hope, if I can't do it, someone using it can.  
One moment...

**Comment by Andrious** [comment]
Done.

**Comment by deadsoul44** [comment]
Thank you
