### ISSUE TITLE
Firebase Auth breaking change - code below to fix

### ISSUE THREAD

**Issue by seancondev** [AndriousSolutions/auth#3]
/// Changed from _fireBaseAuth?.updateProfile(userUpdateInfo) to _user?.updateProfile(userUpdateInfo)
  static Future<void> updateProfile(UserUpdateInfo userUpdateInfo) =>
      _user?.updateProfile(userUpdateInfo);

**Comment by Andrious** [comment]
Has this bee addressed for you?
