### ISSUE TITLE
auth dependency does not resolve

### ISSUE THREAD

**Issue by ride4sun** [AndriousSolutions/auth#5]
I added auth: ^3.2.0 to my pubspec and added the import in my file like this:
import 'package:auth/auth.dart'

I create a reference Auth _auth; I used later in my init code  _auth = Auth.init(...
Not any of these references resolve. I use already google sign in and firebase in that project.
Then I created a blank project and added the reference  - same problem.

'error: Target of URI doesn't exist: 'package:auth/auth.dart'. (uri_does_not_exist at [elm_bluetooth_bloc] lib\bloc\login\login_bloc.dart:3)'
'error: Undefined class 'Auth'. (undefined_class at [elm_bluetooth_bloc] lib\bloc\login\login_bloc.dart:10)'

If I just copy the two files from your project all resolves fine.

C:\Projects>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code, 32-bit edition (version 1.30.1)
[√] Connected device (2 available)

**Comment by Andrious** [comment]
Have you resolved this?

**Comment by ride4sun** [comment]
No, I just used only the firebase packages
