### ISSUE TITLE
flutter_facebook_login instead of facebook web view login

### ISSUE THREAD

**Issue by deadsoul44** [AndriousSolutions/auth#6]
Hello, thanks for the great library.
Is it possible to make use of flutter_facebook_login or implement similar behavior instead of Facebook web view login? Because, in web view login, user has to write email and password manually and as far as I know it will not be auto filled next time user tries to login.

**Comment by Andrious** [comment]
I can't see why not....  I'll take a look into it.

**Comment by Andrious** [comment]
Both the plugins for Facebook and Twitter have now been introduced to the library package.
Turn to the [ChangeLog ](https://pub.dev/packages/auth#-changelog-tab-)for now to determine the recent changes. I will follow-up with an [article ](https://medium.com/@greg.perry)on the subject shortly. Let me know if it's working for you.

**Comment by deadsoul44** [comment]
I will try it in a couple of days. Thank you.

**Comment by deadsoul44** [comment]
It is working. Thank you.
