### ISSUE TITLE
SignInWithGoogle crashes on Android

### ISSUE THREAD

**Issue by melvinm99** [AndriousSolutions/auth#8]
I'm getting this exception on android 9.0 with latest version of this plugin:
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
E/AndroidRuntime( 3132): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime( 3132): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
E/AndroidRuntime( 3132): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
E/AndroidRuntime( 3132): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
E/AndroidRuntime( 3132): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3007)
E/AndroidRuntime( 3132): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3256)
E/AndroidRuntime( 3132): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime( 3132): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 3132): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 3132): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
E/AndroidRuntime( 3132): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3132): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 3132): 	at android.app.ActivityThread.main(ActivityThread.java:7037)
E/AndroidRuntime( 3132): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3132): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime( 3132): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime( 3132): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.guala.koalarm-ZHyc8QrMaukWx9JlaxDelw==/base.apk"],nativeLibraryDirectories=[/data/app/com.guala.koalarm-ZHyc8QrMaukWx9JlaxDelw==/lib/arm64, /data/app/com.guala.koalarm-ZHyc8QrMaukWx9JlaxDelw==/base.apk!/lib/arm64-v8a, /system/lib64]]

**Comment by Andrious** [comment]
I'll take a look right away.

**Comment by Andrious** [comment]
I don't readily see it being an issue with SignInWithGoogle itself.

The error message appears instead to be concern with AndroidX.

I'll leave it to you to research this further on your own: ["Failed resolution of: Landroidx"](https://www.google.com/search?q=%22Failed+resolution+of%3A+Landroidx%22&rlz=1C5CHFA_enCA842CA842&oq=%22Failed+resolution+of%3A+Landroidx%22&aqs=chrome..69i57.6771j0j7&sourceid=chrome&ie=UTF-8)

Stackoverflow is a great resource: [site:stackoverflow.com "Failed resolution of: Landroidx"](https://www.google.com/search?q=site%3Astackoverflow.com+%22Failed+resolution+of%3A+Landroidx%22&rlz=1C5CHFA_enCA842CA842&oq=site%3Astackoverflow.com+%22Failed+resolution+of%3A+Landroidx%22&aqs=chrome..69i57j69i58.10272j0j7&sourceid=chrome&ie=UTF-8)

Github has its uses as well:  [site:github.com "Failed resolution of: Landroidx"](https://www.google.com/search?q=site%3Agithub.com+%22Failed+resolution+of%3A+Landroidx%22&rlz=1C5CHFA_enCA842CA842&oq=site%3Agithub.com+%22Failed+resolution+of%3A+Landroidx%22&aqs=chrome..69i57j69i58.1285j0j7&sourceid=chrome&ie=UTF-8)

**Comment by melvinm99** [comment]
Hi, sorry I was wrong: it was related to my project libs. I solved it by recreating the project.
Thank you
