### ISSUE TITLE
Trying to bring back and save info to Firestore

### ISSUE THREAD

**Issue by leoomoy** [AndriousSolutions/auth#9]
Hi, would it be possible to guide after authentication, I would like get the ID as reference to create more details of the user and send it back again to firestore with more details. Been studying on google auth + firebase. For this how will I? I know my question is a hell stupid, im  self studying on this. Thanks...

**Comment by Andrious** [comment]
The [article](https://github.com/AndriousSolutions/auth#on-medium) referenced in this library package's README may be helpful to you.

In that article, you will find a section called, [It’s Authentic Info](
https://medium.com/@greg.perry/auth-in-flutter-97275b29b550#4b9e).
There it references the class property, `auth.uid`, that supplies the ID of the user as well as many other class properties offered by the library package providing further user information.

**Comment by leoomoy** [comment]
Thank you so much! Im digging into it.
